name: Build on Merge

on:
  push:
    branches: [ develop, main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Gradle cache
        uses: gradle/actions/setup-gradle@v3

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Assemble release-like build
        run: ./gradlew assembleDebug --stacktrace
      # --- Write service account JSON from GitHub Secret to a temp file ---
      - name: Prepare Firebase credentials
        shell: bash
        run: |
          # Write the secret into a file that Gradle can read
          echo "${{ secrets.FIREBASE_CREDENTIALS }}" > /tmp/firebase-creds.json

      # --- Upload APK to Firebase App Distribution ---
      - name: Upload to Firebase App Distribution (debug)
        env:
          # Gradle plugin reads this path in app/build.gradle.kts via System.getenv
          GOOGLE_APPLICATION_CREDENTIALS: /tmp/firebase-creds.json
          # Nice release notes with last commit message (optional)
          GIT_MSG: ${{ github.event.head_commit.message }}
        run: ./gradlew appDistributionUploadDebug --stacktrace
