name: PR Checks

on:
  pull_request:
    branches: [ develop, main, master ]
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Gradle cache
        uses: gradle/actions/setup-gradle@v3

      - name: Make gradlew executable
        run: chmod +x gradlew
        # Note: avoids "Permission denied" on Linux runners

      - name: Lint + Unit tests + Assemble (debug)
        run: |
          # Run typical Android tasks; adjust module if needed (e.g., :app:)
          ./gradlew lintDebug testDebugUnitTest assembleDebug --stacktrace
          # If you also have instrumentation tests, we can add connectedAndroidTest later.
